### ISSUE TITLE
//TODO (Paint-like application)

### ISSUE THREAD

**Issue by Y-LyN-10** [ginovski/Mary-Pickford#1]
The application will be build on canvas (vanilla). It's required also to have a SVG Animation, so let it be the loading bar or or smth like that.

So, we can divide the project as:
- The SVG animation
- Paint UI (panels, menu, canvas, buttons & icons, css-styling, jQuery animations)
- DOM Manipulation (attach events to the buttons)
- Main paint features (It's not required to implement all of them):
  - Color picker
  - Bucket fill
  - Dots, lines, brushes of different size & color
  - Shapes (elipse, rectangles)
  - ZoomIn / ZoomOut
  - Eraser
  - Text (with basic fonts)

If that is not enough, then implement:
- Storage (save the image, load and delete) 
- History (save history of actions and implement the ability to get back some steps)
- Layers (+ move tool, change visibility, delete layers, re-arrange them, etc...)
- Image manipulation tools (upload, change colors, contrast, crop)

**Comment by ginovski** [comment]
-Image Editing(CamanJS)
